# Generated by Django 5.1.6 on 2025-03-31 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_app', '0003_resume_user_chatmessage_delete_chathistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='last_revision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='revision_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='resume',
            name='rewritten_content',
            field=models.TextField(blank=True),
        ),
    ]
